/* Catalog logins — generated by build/make_user.mjs. Password hashes are
   PBKDF2-SHA256 (safe to commit). Never commit AUTH_SECRET — set it in Vercel. */
export default {
  "users": [
    {
      "u": "kuznetsov",
      "name": "Кузнецов В.Е. (владелец)",
      "role": "permanent",
      "expires": null,
      "salt": "PG9hOPRxezG1OKZiLHSzEg",
      "hash": "i3YYuQC--yt7-KXD19vu4Zjmq8MX3-CL5-vinMgyjz0",
      "iters": 120000
    },
    {
      "u": "user",
      "name": "Временный доступ",
      "role": "temporary",
      "expires": "2026-09-22",
      "salt": "octyptgQP5YyWPdZqUG-XA",
      "hash": "hmyUWM3kPs0IKFtMv4eqsuUfm6Ogfj38a5tvmdk7q_0",
      "iters": 120000
    }
  ]
};
